#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &
~/.fehbg
picom --experimental-backends -b
/usr/bin/dunst &
~/.config/polybar/launch.sh &

export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

#external_monitor=$(xrandr --query | grep 'HDMI-0')
#if [[ external_monitor = *connected* ]]; then
    xrandr --output DP-0 --primary --mode 1920x1080 --rate 144.00 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --right-of DP-0
    bspc monitor DP-0 -d I II III IV V
    bspc monitor HDMI-0 -d VI VII VIII IX X
#else
#    xrandr --output DP-0 --mode 1920x1080 --rate 144.00
#    bspc monitor -d I II III IV V VI VIII IX X
#fi

bspc config border_width         2
bspc config window_gap          10
bspc config focus_follows_pointer true
bspc config active_border_color "#29303e"
bspc config normal_border_color "#3e4b65"
bspc config focused_border_color "#50A6EC"
bspc config presel_feedback_color "#48AFB8"

bspc wm --adopt-orphans

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled 
